name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests with tox
      run: tox -e py${{ matrix.python-version }}

    - name: Check for coverage.xml file
      run: |
        if [ -f coverage.xml ]; then
          echo "coverage.xml exists at $(pwd)"
        else
          echo "coverage.xml does not exist in $(pwd)"
          ls -la  # List files to debug
          exit 1  # Fail the job if coverage.xml does not exist
        fi
      shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
